<a href="https://colab.research.google.com/github/samuel76-art/Disciplina-de-Inteligencia-Artificial-UMC/blob/main/Atividades_de_Data_Science_NumPy%2C_SciPy%2C_Pandas_e_Matplotlib%5BSamuel_Sousa_Santos%5D%5BB%5D%5BNoite%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np
# Raciocinio - Uso np.random.randint(baixo, alto, tamanho) para gerar valores inteiros dentro de um intervalo. O limite superior em randint e exclusivo, por isso uso 101 para incluir o 100.
# Gerando array de 50 inteiros entre 10 e 100
arrayNumeros = np.random.randint(10, 101, 50)
print("Array de 50 numeros aleatorios entre 10 e 100:")
print(arrayNumeros)

Array de 50 numeros aleatorios entre 10 e 100:
[77 31 80 91 17 82 98 31 56 17 60 59 81 59 71 26 38 31 46 68 64 75 45 49
 80 77 37 92 90 47 48 12 56 46 57 75 49 45 80 71 35 78 28 23 38 48 40 68
 91 21]


In [41]:
import numpy as np
# Raciocinio - Gero os numeros de 1 a 16 com np.arange e uso .reshape(4, 4) para organiza-los em uma matriz 4x4. A ultima linha e acessada com indice -1.
# Criando a matriz 4x4 e extraindo a ultima linha
matriz = np.arange(1, 17).reshape(4, 4)
print("Matriz 4x4:")
print(matriz)
ultimaLinha = matriz[-1]
print("\nUltima linha:", ultimaLinha)

Matriz 4x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Ultima linha: [13 14 15 16]


In [43]:
import numpy as np
# Raciocinio - Crio um array de 15 zeros com np.zeros(15). Como a indexacao comeca em 0, a 5ª posicao corresponde ao indice 4 e a 10ª ao indice 9; uso slicing [4:10] para substituir esse intervalo por 1 de uma vez.
# Criando o array e substituindo o intervalo
arrayZeros = np.zeros(15)
arrayZeros[4:10] = 1
print("Array com a 5ª a 10ª posicao substituida por 1:")
print(arrayZeros)

Array com a 5ª a 10ª posicao substituida por 1:
[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [45]:
import numpy as np
# Raciocinio - Gero 100 inteiros aleatorios e uso np.median() para a mediana (valor central quando os dados estao ordenados). NumPy nao tem uma funcao nativa de moda, entao uso np.bincount() combinado com np.argmax(), que conta a frequencia de cada valor e retorna o indice (valor) mais frequente.
# Gerando 100 inteiros e calculando mediana e moda
arrayNumeros = np.random.randint(0, 100, 100)
medianaArray = np.median(arrayNumeros)
contagensValores = np.bincount(arrayNumeros)
modaArray = np.argmax(contagensValores)
print("Array:", arrayNumeros)
print("\nMediana:", medianaArray)
print("Moda:", modaArray)

Array: [56 44 10 28 77 99 89 70 62 60 79 65 95 27 38 12 91 77 29 14 64 58 89 12
 74 42  4 71 76 74  7 72 67 89 93 53 54 68 52 26 30 39 94 68 78 86 25 79
 83 43  0 75 82 85 75 65 48  2 43 71 42 65 21 39 22  6 19 20 30 44 57 67
 73 32 86 67 76 86 75 60 91 78  2  7 71  2  7 15 91  7 93 89 11 46 21  9
 68 46 58  0]

Mediana: 59.0
Moda: 7


In [46]:
import numpy as np
# Raciocinio - Gero um array de 20 elementos entre 1 e 100 e uso indexacao booleana: array % 3 == 0 cria uma mascara True/False que identifica os multiplos de 3, e a atribuicao array[mascara] = -3 substitui so esses valores, sem precisar de laco explicito.
# Gerando o array e substituindo multiplos de 3 por -3
arrayNumeros = np.random.randint(1, 101, 20)
print("Array original:", arrayNumeros)
arrayNumeros[arrayNumeros % 3 == 0] = -3
print("Array com multiplos de 3 substituidos por -3:", arrayNumeros)

Array original: [80 57 11 29 26 74 21 31 14 41 23 53 68 66 90 73 87 54 10 65]
Array com multiplos de 3 substituidos por -3: [80 -3 11 29 26 74 -3 31 14 41 23 53 68 -3 -3 73 -3 -3 10 65]


In [47]:
import numpy as np
# Raciocinio - Gero uma matriz 5x5 com np.random.rand() (valores entre 0 e 1) e uso np.sum(matriz, axis=0). O parametro axis=0 indica que a soma deve ser feita ao longo das linhas (ou seja, coluna por coluna).
# Gerando a matriz 5x5 e somando por colunas
matrizNumeros = np.random.rand(5, 5)
print("Matriz:")
print(matrizNumeros)
somaColunas = np.sum(matrizNumeros, axis=0)
print("\nSoma de cada coluna:", somaColunas)

Matriz:
[[0.7737103  0.77962688 0.8563082  0.20109176 0.8358794 ]
 [0.8731478  0.66196842 0.5545219  0.79974408 0.76388628]
 [0.50401745 0.16669687 0.52675356 0.23217684 0.04353961]
 [0.66468602 0.35827297 0.10304853 0.89787621 0.25153804]
 [0.68946601 0.75209921 0.22580066 0.26526632 0.76445948]]

Soma de cada coluna: [3.50502758 2.71866434 2.26643286 2.39615521 2.65930282]


In [51]:
import numpy as np
# Raciocinio - Uso np.corrcoef(arrayA, arrayB), que retorna uma matriz de correlacao 2x2 — a posicao [0, 1] (ou [1, 0]) contem o coeficiente de correlacao entre os dois arrays, que varia de -1 (correlacao negativa perfeita) a 1 (correlacao positiva perfeita).
# Gerando dois arrays aleatorios e calculando a correlacao
arrayA = np.random.rand(20)
arrayB = np.random.rand(20)
matrizCorrelacao = np.corrcoef(arrayA, arrayB)
coeficienteCorrelacao = matrizCorrelacao[0, 1]
print("Correlacao entre os arrays:", coeficienteCorrelacao)

Correlacao entre os arrays: -0.27755602146721003


In [52]:
import numpy as np
# Raciocinio - Gero uma matriz 3x3 de inteiros aleatorios e uso o operador ** 2, que no NumPy e aplicado elemento a elemento (operacao vetorizada) — nao e necessario laco para percorrer a matriz manualmente.
# Gerando a matriz 3x3 e elevando seus elementos ao quadrado
matrizOriginal = np.random.randint(1, 20, (3, 3))
print("Matriz original:")
print(matrizOriginal)
matrizQuadrado = matrizOriginal ** 2
print("\nMatriz elevada ao quadrado:")
print(matrizQuadrado)

Matriz original:
[[ 4  1 17]
 [19 10 18]
 [12  7  3]]

Matriz elevada ao quadrado:
[[ 16   1 289]
 [361 100 324]
 [144  49   9]]


In [65]:
import numpy as np
# Raciocinio - A normalizacao Min-Max transforma qualquer valor x em (x - minimo) / (maximo - minimo), garantindo que o menor valor vire 0 e o maior vire 1. Uso np.set_printoptions(linewidth=100) e imprimo o texto separado do array para evitar quebras e espacamentos indesejados.
# Gerando o array e aplicando a normalizacao Min-Max
np.set_printoptions(linewidth=100)
arrayOriginal = np.random.randint(1, 100, 10).astype(float)
print("Array original:")
print(arrayOriginal)
arrayNormalizado = (arrayOriginal - arrayOriginal.min()) / (arrayOriginal.max() - arrayOriginal.min())
print("\nArray normalizado entre 0 e 1:")
print(np.round(arrayNormalizado, 4))

Array original:
[62. 37. 34. 20. 35. 38. 34. 78. 47. 88.]

Array normalizado entre 0 e 1:
[0.6176 0.25   0.2059 0.     0.2206 0.2647 0.2059 0.8529 0.3971 1.    ]


In [66]:
import numpy as np
# Raciocinio - Crio a matriz identidade com np.eye(6) e depois uso np.fill_diagonal() para substituir os valores da diagonal principal (que originalmente sao todos 1) pela sequencia de 1 a 6.
# Criando a matriz e alterando a diagonal principal
matrizIdentidade = np.eye(6)
np.fill_diagonal(matrizIdentidade, np.arange(1, 7))
print("Matriz identidade 6x6 com diagonal de 1 a 6:")
print(matrizIdentidade)

Matriz identidade 6x6 com diagonal de 1 a 6:
[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]


In [67]:
import numpy as np
# Raciocinio - Mesma logica do exercicio 4 (calculo de moda): np.bincount() conta quantas vezes cada valor aparece, e np.argmax() retorna o valor (indice) com maior contagem — ou seja, o mais frequente.
# Gerando o array e encontrando o valor mais frequente
arrayNumeros = np.random.randint(0, 20, 100)
contagensValores = np.bincount(arrayNumeros)
maisRepetido = np.argmax(contagensValores)
print("Array:")
print(arrayNumeros)
print("\nValor mais repetido:", maisRepetido, "- apareceu", contagensValores[maisRepetido], "vezes")

Array:
[ 9 17  8 12 18  0 19 19  6 19 18 16 13  8 19  0  1  6  8 18  7 17 15 18 17  1 14  8  2 15  3 13  2
 17 17  7 10 13 10 14  0  4 13  4 14  6  2 18  3  0 10 16 19 14 17 16  0  4 11 10  1  3 15  3 11 11
 10 18 17 17  4  5 14  6  4  2 19  8  7 13 15  5 12 14  1 17  9 16  6 17  5 16  4  6 10  2 13 11 12
  9]

Valor mais repetido: 17 - apareceu 10 vezes


In [68]:
import numpy as np
# Raciocinio - Uso np.fill_diagonal(matriz, 7), que substitui diretamente todos os elementos da diagonal principal por um valor fixo — mais direto do que percorrer a matriz com lacos aninhados testando i == j.
# Gerando a matriz 4x4 e substituindo a diagonal por 7
matrizOriginal = np.random.randint(1, 10, (4, 4))
print("Matriz original:")
print(matrizOriginal)
np.fill_diagonal(matrizOriginal, 7)
print("\nMatriz com diagonal substituida por 7:")
print(matrizOriginal)

Matriz original:
[[7 3 4 8]
 [8 2 8 3]
 [7 8 2 7]
 [2 8 9 4]]

Matriz com diagonal substituida por 7:
[[7 3 4 8]
 [8 7 8 3]
 [7 8 7 7]
 [2 8 9 7]]


In [70]:
import numpy as np
# Raciocinio - Gero os 10 primeiros pares com np.arange(2, 21, 2) (comeca em 2, vai ate 20, de 2 em 2) e uso np.cumsum(), que retorna um array onde cada posicao e a soma de todos os elementos ate ali — util para ver o acumulo progressivo.
# Gerando os numeros pares e calculando a soma cumulativa
arrayPares = np.arange(2, 21, 2)
print("10 primeiros numeros pares:")
print(arrayPares)
somaCumulativa = np.cumsum(arrayPares)
print("\nSoma cumulativa:")
print(somaCumulativa)

10 primeiros numeros pares:
[ 2  4  6  8 10 12 14 16 18 20]

Soma cumulativa:
[  2   6  12  20  30  42  56  72  90 110]


In [71]:
import numpy as np
# Raciocinio - Como os dois arrays tem o mesmo tamanho, a subtracao arrayA - arrayB e feita elemento a elemento automaticamente. Depois, .mean() calcula a media dessas diferencas.
# Gerando os dois arrays e calculando a media das diferencas
arrayA = np.random.randint(1, 100, 20)
arrayB = np.random.randint(1, 100, 20)
diferencas = arrayA - arrayB
mediaDiferencas = diferencas.mean()
print("Array A:")
print(arrayA)
print("\nArray B:")
print(arrayB)
print("\nMedia das diferencas:", mediaDiferencas)

Array A:
[ 2 53 55 85 81 64 88 87 52 81 73 96 95 35 17  6 80 67  3 28]

Array B:
[74 26  5 66 87 40 43  5 57 46 63 13 19 38 34 95 92 68 16 74]

Media das diferencas: 9.35


In [72]:
import numpy as np
# Raciocinio - Uso indexacao booleana novamente: arrayNumeros > 50 cria a mascara dos valores acima do limite, e a atribuicao arrayNumeros[mascara] = 50 limita (faz um "clipping" manual) esses valores. O NumPy tambem tem np.clip() pronto para isso, mas aqui uso a abordagem manual para reforcar o conceito de mascara booleana.
# Gerando o array e limitando valores maiores que 50
arrayNumeros = np.random.randint(1, 100, 20)
print("Array original:")
print(arrayNumeros)
arrayNumeros[arrayNumeros > 50] = 50
print("\nArray com valores > 50 limitados a 50:")
print(arrayNumeros)

Array original:
[69 57 69 62 84 95 16 36 62 49 30 99 26  6 93 66 51 30 90 55]

Array com valores > 50 limitados a 50:
[50 50 50 50 50 50 16 36 50 49 30 50 26  6 50 50 50 30 50 50]


In [73]:
import numpy as np
# Raciocinio - Crio um array de 12 elementos (necessario, pois 3 x 4 = 12) e uso .reshape(3, 4) para reorganiza-lo em uma matriz com 3 linhas e 4 colunas, mantendo a ordem original dos elementos.
# Gerando o array de 12 elementos e aplicando o reshape
arrayNumeros = np.arange(1, 13)
print("Array original:")
print(arrayNumeros)
matrizReshaped = arrayNumeros.reshape(3, 4)
print("\nReorganizado em matriz 3x4:")
print(matrizReshaped)

Array original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reorganizado em matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [74]:
import numpy as np
# Raciocinio - Interpreto "posicao" como o indice sequencial de cada celula (0 a 15) ao percorrer a matriz. Crio uma matriz de indices com np.arange(16).reshape(4, 4) e multiplico elemento a elemento pela matriz original.
# Gerando a matriz 4x4, a matriz de posicoes e realizando a multiplicacao
matrizOriginal = np.random.randint(1, 10, (4, 4))
matrizPosicoes = np.arange(16).reshape(4, 4)
matrizResultado = matrizOriginal * matrizPosicoes
print("Matriz original:")
print(matrizOriginal)
print("\nMatriz de posicoes (0 a 15):")
print(matrizPosicoes)
print("\nResultado (valor x posicao):")
print(matrizResultado)

Matriz original:
[[8 7 8 3]
 [6 4 4 9]
 [1 2 9 5]
 [9 2 6 4]]

Matriz de posicoes (0 a 15):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Resultado (valor x posicao):
[[  0   7  16   9]
 [ 24  20  24  63]
 [  8  18  90  55]
 [108  26  84  60]]


In [75]:
import numpy as np
# Raciocinio - Mesma tecnica de mascara booleana usada nos exercicios 5 e 15: arrayNumeros % 5 == 0 identifica os multiplos de 5, que sao substituidos por 0.
# Gerando o array e substituindo multiplos de 5 por 0
arrayNumeros = np.random.randint(1, 100, 10)
print("Array original:")
print(arrayNumeros)
arrayNumeros[arrayNumeros % 5 == 0] = 0
print("\nArray com multiplos de 5 substituidos por 0:")
print(arrayNumeros)

Array original:
[62 75 10 36 62 27 52 88 61 92]

Array com multiplos de 5 substituidos por 0:
[62  0  0 36 62 27 52 88 61 92]


In [76]:
import numpy as np
# Raciocinio - O cosseno do angulo entre dois vetores e dado por cos(theta) = (a.b) / (|a| |b|), onde a.b e o produto escalar (np.dot) e |a|, |b| sao as normas (magnitudes) dos vetores (np.linalg.norm). Depois de calcular o cosseno, uso np.arccos() para obter o angulo em radianos, e converto para graus com np.degrees() para facilitar a leitura.
# Gerando dois arrays e calculando o angulo entre eles
arrayA = np.random.randint(1, 20, 20)
arrayB = np.random.randint(1, 20, 20)
cosTheta = np.dot(arrayA, arrayB) / (np.linalg.norm(arrayA) * np.linalg.norm(arrayB))
anguloRadianos = np.arccos(cosTheta)
anguloGraus = np.degrees(anguloRadianos)
print("Angulo entre os arrays:")
print(f"{anguloGraus:.2f} graus")

Angulo entre os arrays:
40.46 graus


In [77]:
import numpy as np
# Raciocínio - Uso np.min(matrizOriginal, axis=1). O parâmetro axis=1 indica que a operação deve percorrer cada linha (ao longo das colunas), retornando um valor mínimo por linha.
# Gerando a matriz 5x5 e encontrando o valor mínimo de cada linha
matrizOriginal = np.random.randint(1, 100, (5, 5))
print("Matriz:")
print(matrizOriginal)
minimosPorLinha = np.min(matrizOriginal, axis=1)
print("\nValor mínimo de cada linha:")
print(minimosPorLinha)

Matriz:
[[23 99 24 74 69]
 [ 7 93 31 99 70]
 [37  7 25 76 83]
 [30 10  6 27 35]
 [67 79 52 14 13]]

Valor mínimo de cada linha:
[23  7  7  6 13]


In [82]:
#Exercícios de SciPy -  Integral de f(x) = x² sin(x) de 0 a π
import numpy as np
from scipy import integrate
# Raciocínio - Uso scipy.integrate.quad(), que calcula integrais definidas numericamente. Passo a função f(x) = x² * sin(x), o limite inferior (0) e o superior (π, obtido de np.pi).
# Definindo a função e realizando a integração
def f(x):
    return (x**2) * np.sin(x)
resultado, erro = integrate.quad(f, 0, np.pi)
print("Integral de x² sin(x) de 0 a π:")
print(f"Resultado: {resultado:.6f}")
print(f"Erro estimado: {erro:.2e}")

Integral de x² sin(x) de 0 a π:
Resultado: 5.869604
Erro estimado: 6.52e-14


In [88]:
import numpy as np
from scipy.integrate import solve_ivp
# Raciocínio - Uso scipy.integrate.solve_ivp() para resolver a equação diferencial ordinária numericamente. Defino a função que representa dy/dx em termos de x e y, passo o intervalo [0, 10] e a condição inicial y(0) = 1. t_eval define os pontos onde quero ver a solução.
# Definindo a equação diferencial e resolvendo o PVI (Problema de Valor Inicial)
def eq_diferencial(x, y):
    return x - y
solucao = solve_ivp(eq_diferencial, [0, 10], [1], t_eval=np.linspace(0, 10, 50))
print("Valores de x:")
print(solucao.t)
print("\nValores de y:")
print(solucao.y[0])

Valores de x:
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816  1.2244898   1.42857143
  1.63265306  1.83673469  2.04081633  2.24489796  2.44897959  2.65306122  2.85714286  3.06122449
  3.26530612  3.46938776  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735  6.12244898  6.32653061
  6.53061224  6.73469388  6.93877551  7.14285714  7.34693878  7.55102041  7.75510204  7.95918367
  8.16326531  8.36734694  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]

Valores de y:
[1.         0.83473665 0.73748092 0.69627063 0.70060169 0.7414494  0.81232517 0.90794779 1.02364878
 1.15547018 1.30059252 1.45674873 1.6218705  1.79408816 1.97197207 2.15469899 2.34151958 2.531691
 2.72447686 2.91916406 3.11538128 3.31302011 3.51194215 3.71197332 3.91290391 4.11448851 4.31644608
 4.51856038 4.72090685 4.92353654 5.12647358 5.32971751 5.5332432

In [95]:
import numpy as np
# Raciocínio - Como essa é uma função polinomial, uso np.roots(), que recebe os coeficientes do polinômio (do maior para o menor grau) e retorna todas as raízes de uma vez.
# Coeficientes de x^4 - 3x^3 + 0x^2 + 0x + 2
coeficientes = [1, -3, 0, 0, 2]
raizes = np.roots(coeficientes)
print("Raízes de f(x) = x⁴ - 3x³ + 2:")
for r in raizes:
    if np.isreal(r):
        print(f"{r.real:.4f}")
    else:
        print(f"{r:.4f}")

Raízes de f(x) = x⁴ - 3x³ + 2:
2.9196
1.0000
-0.4598+0.6882j
-0.4598-0.6882j


In [104]:
import numpy as np
from scipy.optimize import minimize
# Raciocínio - O SciPy só tem funções de minimização prontas (como optimize.minimize), então para maximizar f(x) minimizamos o seu negativo (-f(x)). O ponto x que minimiza -f(x) é o mesmo que maximiza f(x).
def f(x):
    return -(x**2) + 4*x + 1

def f_negativa(x):
    return -f(x)
# Chute inicial em x = 0
resultado = minimize(f_negativa, x0=0)
x_otimo = resultado.x[0]
y_max = f(x_otimo)
print("x que maximiza f(x):")
print(f"{x_otimo:.4f}")
print("\nValor máximo de f(x):")
print(f"{y_max:.4f}")

x que maximiza f(x):
2.0000

Valor máximo de f(x):
5.0000


In [109]:
import numpy as np
from scipy.fft import fft, fftfreq
# Raciocínio - Gero o sinal combinando as duas ondas no tempo (t de 0 a 1s com 500 amostras) e uso scipy.fft.fft() para converter do domínio do tempo para o domínio da frequência. Também uso fftfreq para obter o eixo de frequências associado.
N = 500
t = np.linspace(0, 1, N, endpoint=False)
sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)
# Cálculo da FFT e das frequências correspondentes
frequencias = fft(sinal)
eixo_freq = fftfreq(N, d=1/N)
print("Transformada de Fourier (primeiros 10 coeficientes complexos):")
print(frequencias[:10])
print("\nMagnitude dos primeiros 10 coeficientes:")
print(np.abs(frequencias[:10]))

Transformada de Fourier (primeiros 10 coeficientes complexos):
[-8.32667268e-15-0.00000000e+00j -2.20934382e-14-2.50000000e+02j  2.50000000e+02-3.41948692e-14j
  1.56045512e-14-6.62279098e-15j -1.13100615e-14-3.29398128e-15j  1.49350723e-14+6.72363081e-15j
 -1.56694156e-14+3.21843834e-14j -2.15025550e-14-2.61373100e-14j  8.27384792e-16+5.94566511e-15j
 -3.22862859e-14-1.99725923e-14j]

Magnitude dos primeiros 10 coeficientes:
[8.32667268e-15 2.50000000e+02 2.50000000e+02 1.69517957e-14 1.17799746e-14 1.63787544e-14
 3.57961606e-14 3.38455144e-14 6.00295753e-15 3.79645717e-14]
