<a href="https://colab.research.google.com/github/samuel76-art/Disciplina-de-Inteligencia-Artificial-UMC/blob/main/Atividades_de_Data_Science_NumPy%2C_SciPy%2C_Pandas_e_Matplotlib%5BSamuel_Sousa_Santos%5D%5BB%5D%5BNoite%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Exercıcios de NumPy
import numpy as np
#Raciocinio - Uso np.random.randint(baixo, alto, tamanho) para gerar valores inteiros dentro de um intervalo. O limite superior em randint e exclusivo, por isso uso 101 para incluir o 100.
#Gerando array de 50 inteiros entre 10 e 100
array = np.random.randint(10, 101, 50)
print("Array de 50 numeros aleatorios entre 10 e 100:")
print(array)

Array de 50 números aleatórios entre 10 e 100:
[ 79  54  45  67  49  91  51  70  62  20  80  74  97  82  26  29  27  80
 100  81  50  98  42  79  41  40  67  74  31  23  16  86  75  74  65  90
  11  25  91  42  80  14  58  60  65  14  72  75  97  56]


In [3]:
import numpy as np
# Raciocinio - Gero os números de 1 a 16 com np.arange e uso .reshape(4, 4) para organizá-los em uma matriz 4x4. A última linha é acessada com índice -1.
# Criando a matriz 4x4 e extraindo a última linha
matriz = np.arange(1, 17).reshape(4, 4)
print("Matriz 4x4:")
print(matriz)
ultima_linha = matriz[-1]
print("\nÚltima linha:", ultima_linha)

Matriz 4x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha: [13 14 15 16]


In [5]:
import numpy as np
# Raciocinio - Crio um array de 15 zeros com np.zeros(15). Como a indexação começa em 0, a 5ª posição corresponde ao índice 4 e a 10ª ao índice 9; uso slicing [4:10] para substituir esse intervalo por 1 de uma vez.
# Criando o array e substituindo o intervalo
array = np.zeros(15)
array[4:10] = 1
print("Array com a 5ª à 10ª posição substituída por 1:")
print(array)

Array com a 5ª à 10ª posição substituída por 1:
[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
# Raciocinio - Gero 100 inteiros aleatorios e uso np.median() para a mediana (valor central quando os dados estao ordenados). NumPy nao tem uma funcao nativa de moda, entao uso np.bincount() combinado com np.argmax(), que conta a frequência de cada valor e retorna o índice (valor) mais frequente.
# Gerando 100 inteiros e calculando mediana e moda
array = np.random.randint(0, 100, 100)
mediana = np.median(array)
contagens = np.bincount(array)
moda = np.argmax(contagens)
print("Array:", array)
print("\nMediana:", mediana)
print("Moda:", moda)

Array: [95 96  2 83 69 11 24 12 22 90 88 29 60 65 13 77 51 15 29  4 94 79 54  3
 48  6 55 22 41 70 31  1 45 18 17 12 61 64  7 23 27 61 35 59 17 86  6  6
 75 68 16 48 50 69 39 47 94 65 95 47 49 58 66  3 69 50 70 39 23 15 32 65
 31 63 84 67 85 53  7 25 56 11 55 54 55 70 53 34 27 28  2 29 95 18 73 63
 80 64 48 10]

Mediana: 48.5
Moda: 6


In [7]:
import numpy as np
# Raciocinio - Gero um array de 20 elementos entre 1 e 100 e uso indexação booleana: array % 3 == 0 cria uma máscara True/False que identifica os múltiplos de 3, e a atribuição array[mascara] = -3 substitui só esses valores, sem precisar de laço explícito.
# Gerando o array e substituindo multiplos de 3 por -3
array = np.random.randint(1, 101, 20)
print("Array original:", array)
array[array % 3 == 0] = -3
print("Array com multiplos de 3 substituidos por -3:", array)

Array original: [30 61 35 77 34 13 74 48 58  5 58 62 70 77 83 99 98 26 43 33]
Array com múltiplos de 3 substituídos por -3: [-3 61 35 77 34 13 74 -3 58  5 58 62 70 77 83 -3 98 26 43 -3]


In [8]:
import numpy as np
# Raciocinio - Gero uma matriz 5x5 com np.random.rand() (valores entre 0 e 1) e uso np.sum(matriz, axis=0). O parametro axis=0 indica que a soma deve ser feita ao longo das linhas (ou seja, coluna por coluna).
# Gerando a matriz 5x5 e somando por colunas
matriz = np.random.rand(5, 5)
print("Matriz:")
print(matriz)
soma_colunas = np.sum(matriz, axis=0)
print("\nSoma de cada coluna:", soma_colunas)

Matriz:
[[0.86437916 0.41715772 0.81682042 0.70133269 0.39757857]
 [0.83132057 0.49659043 0.04469205 0.03412014 0.6190808 ]
 [0.13226409 0.60214627 0.23512616 0.67198031 0.22650094]
 [0.52498021 0.00650084 0.36706578 0.50447301 0.13131369]
 [0.83291958 0.56253083 0.18235794 0.34682657 0.30647072]]

Soma de cada coluna: [3.1858636  2.0849261  1.64606235 2.25873272 1.68094472]


In [9]:
import numpy as np
# Raciocinio - Uso np.corrcoef(a, b), que retorna uma matriz de correlacao 2x2 — a posicao [0, 1] (ou [1, 0]) contem o coeficiente de correlacao entre os dois arrays, que varia de -1 (correlacao negativa perfeita) a 1 (correlacao positiva perfeita).
# Gerando dois arrays aleatorios e calculando a correlacao
a = np.random.rand(20)
b = np.random.rand(20)
correlacao = np.corrcoef(a, b)[0, 1]
print("Correlacao entre os arrays:", correlacao)

Correlacao entre os arrays: -0.2507934831467209


In [10]:
import numpy as np
# Raciocinio - Gero uma matriz 3x3 de inteiros aleatorios e uso o operador ** 2, que no NumPy e aplicado elemento a elemento (operacao vetorizada) — nao e necessario laco para percorrer a matriz manualmente.
# Gerando a matriz 3x3 e elevando seus elementos ao quadrado
matriz = np.random.randint(1, 20, (3, 3))
print("Matriz original:")
print(matriz)
matriz_quadrado = matriz ** 2
print("\nMatriz elevada ao quadrado:")
print(matriz_quadrado)

Matriz original:
[[12  8 10]
 [ 8 11 16]
 [16  8 13]]

Matriz elevada ao quadrado:
[[144  64 100]
 [ 64 121 256]
 [256  64 169]]
